export * from './geners.interface'
export * from './genre.interface'
export * from './movie.interface'
export * from './pagination.interface'
export * from './search.movie'
export * from './details.movie'